baseURL = "/"
languageCode = "en-us"
title = "CCM's DesignFeed"
theme = "rad-theme"
enableGitInfo = true
canonifyURLs = true

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[build]
  writeStats = true 