baseURL = "/"
languageCode = "en-us"
title = "RAD Reads Collections"
theme = "rad-theme"
enableGitInfo = true

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[build]
  writeStats = true 